# config file for the applicaiton to talk with docker-engine 
# busybox is a very small linux distribution
from python
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
CMD ["python","/app/app.py"] 


