version: '3'
services:
  web:
    build:
      context: static
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
  # Add more services if needed
